### ISSUE TITLE
Pandemic Tracker App

### ISSUE THREAD

**Issue by piyushkhurana2019** [priyankarpal/ProjectsHut#2037]
### Add a new project to the list

It is a Pandemic Tracker App which Shows the no. of infected cases around the globe and displays the top health guidelines to the user
Tech stack:- Map API, news Api, HTML, CSS, JS

<img width="1436" alt="Screenshot 2023-08-06 at 6 34 03 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/96003210/6cc07ec6-a592-41a6-8da2-e36bd298c7c4">

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue
